openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
  description: A simple API to manage todos

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /todo:
    get:
      summary: Get a list of todos
      parameters:
        - name: offset
          in: query
          description: Number of items to skip
          schema:
            type: integer
        - name: limit
          in: query
          description: Number of items to retrieve
          schema:
            type: integer
        - name: title
          in: query
          description: Filter todos by title
          schema:
            type: string
        - name: description
          in: query
          description: Filter todos by description
          schema:
            type: string
      responses:
        '200':
          description: A list of todos
          content:
            application/json:
              schema:
                type: object
                properties:
                  Query:
                    type: object
                    properties:
                      offset:
                        type: integer
                      limit:
                        type: integer
                      Total:
                        type: integer
                  Data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Todo'
        '404':
          description: No todos found
    post:
      summary: Create a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
      responses:
        '200':
          description: Todo created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Todo'
        '400':
          description: Failed to save the todo

  /todo/{id}:
    get:
      summary: Get a todo by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single todo
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found
    put:
      summary: Update a todo by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found
    delete:
      summary: Delete a todo by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Todo deleted successfully
        '404':
          description: Todo not found

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        is_completed:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    TodoInput:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        is_completed:
          type: boolean
